swagger: "2.0.0"
info:
  title: Tina Configurations
  summary: Officical Zeeq Analytics for TINA
  description: Api Documentation for Tina App Zeeq
  version: 1.0.0
  contact:
    email: choudharysidharth082000@gmail.com
  servers:
    - url: "http://localhost:3000"
      description: "Local Server Running"
    - url: "https://testcyberflow.herokuapp.com"
      description: "Main Server"

schemes: [http, https]

paths:
  /v1/testApi:
    get:
      tags:
        - Test
      summary: Test Api
      description: Return HEllo world
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /api/v1/testAPI/checkUserLogin:
    get:
      tags:
        - Test
      summary: Test Api
      description: Return HEllo world
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login to the system
      parameters:
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/signup:
    post:
      tags:
        - Auth
      summary: Signup
      description: Signup to the system
      parameters:
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              nameUser:
                type: string
              email:
                type: string
              password:
                type: string
              confirmPassword:
                type: string
              usertype:
                type: string
              mobileNumber:
                type: string
              userName:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
